name: Build and deploy Kivy app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cython
        run: pip install cython

      
      - uses: actions/checkout@v3

      - name: Install Buildozer
        run: pip install buildozer

      - name: Build the Kivy app
        run: buildozer android debug

      - name: Deploy the Kivy app
        run: adb install -r dist/android/app-debug.apk
